### ISSUE TITLE
[S1 - PBI2] Melihat Daftar dan Memilih Pasar

### ISSUE THREAD

**Issue by muthiqonita** [SI-RPL-2022/SI4305_C_PanganKoeh#5]
Guest / User dapat melihat daftar pasar dan memilih pasar untuk dilihat detailnya

**Comment by CindyMuhdiantini** [comment]
Mockup memilih daftar pasar
![image](https://user-images.githubusercontent.com/92096711/161728263-7967ebaa-af7c-448b-8cbe-ff08bd1b7384.png)
